# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05myapp\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x0cUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.myapp.User\"\x1e\n\rUploadSummary\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"+\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xdd\x01\n\x0bUserService\x12\x32\n\x07GetUser\x12\x12.myapp.UserRequest\x1a\x13.myapp.UserResponse\x12\x32\n\tListUsers\x12\x16.google.protobuf.Empty\x1a\x0b.myapp.User0\x01\x12\x32\n\x0bUploadUsers\x12\x0b.myapp.User\x1a\x14.myapp.UploadSummary(\x01\x12\x32\n\x04\x43hat\x12\x12.myapp.ChatMessage\x1a\x12.myapp.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=84
  _globals['_USER']._serialized_end=183
  _globals['_USERREQUEST']._serialized_start=185
  _globals['_USERREQUEST']._serialized_end=210
  _globals['_USERRESPONSE']._serialized_start=212
  _globals['_USERRESPONSE']._serialized_end=253
  _globals['_UPLOADSUMMARY']._serialized_start=255
  _globals['_UPLOADSUMMARY']._serialized_end=285
  _globals['_CHATMESSAGE']._serialized_start=287
  _globals['_CHATMESSAGE']._serialized_end=330
  _globals['_USERSERVICE']._serialized_start=333
  _globals['_USERSERVICE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
