[project]
name = "websocket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "channels-redis>=4.3.0",
    "channels[daphene,daphne]>=4.3.1",
    "django>=5.2.6",
    "django-admin>=2.0.2",
    "unicorn>=2.1.4",
]
